##################################
#  스프링 부트 속성
##################################
spring:
  config:
    import:
      - classpath:application-database.yml
      - classpath:application-server.yml
      - classpath:application-thymeleaf.yml
      - classpath:application-url.yml
  application:
    name: playlist-web


