##################################
#  스프링 부트 속성
##################################
spring:
  application:
    name: playlist-web

##################################
#  Server
##################################
server:
  port: 8081
